name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Setup env
        run: cp .env-ci .env

      - name: Start postgres db for PG test
        run: docker-compose up -d

      - run: npm install
      - run: npm run-script lit
      - run: npm run-script build
      - run: npm run-script test
