name: CI

on:
  push:
    # branches: master
    branches: ci
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.13.8"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - run: npm install
      - run: npm run-script lit
      - run: npm run-script build
      - run: npm run-script test
